
name: Browser Tests And Coverage

on:
  push:
    branches: [ master ]

  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [12, 14, 16]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: "${{ matrix.node }}"

      - name: Setup Yarn
        uses: sergioramos/yarn-actions@v6
        with:
          no-lockfile: true
          version: true

      - name: Install Dependencies
        run: yarn

      - name: Run Tests
        run: |
          yarn ci
          yarn api-doc:test
          yarn global add codecov && codecov --disable=gcov -f coverage/lcov.info -F unit

  browsers:
    name: Browser Tests
    runs-on: ubuntu-latest

    env:
      BROWSER_PROVIDER_READY_FILE: /tmp/sauce-connect-ready
      LOGS_DIR: /tmp/logs

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 16

      - name: Setup Yarn
        uses: sergioramos/yarn-actions@v6
        with:
          no-lockfile: true
          version: true

      - name: Install Dependencies
        run: yarn

      - name: Saucelabs Connect
        run: |
          mkdir -p $LOGS_DIR
          ./scripts/sauce_connect_setup.sh
          ./scripts/sauce_connect_block.sh

#      - name: Saucelabs Connect
#        uses: saucelabs/sauce-connect-action@v1
#        with:
#          username: "${{ secrets.SAUCE_USERNAME }}"
#          accessKey: "${{ secrets.SAUCE_ACCESS_KEY }}"
#          tunnelIdentifier: "${{ github.run_id }}"
#          scVersion: 4.6.4
#          doctor: true

      - name: Run Browser Tests
        env:
          TRAVIS_BUILD_NUMBER: "${{ github.run_number }}"
          TRAVIS_BUILD_ID: "${{ github.run_id }}"
        run: |
          yarn saucelabs
          yarn saucelabs:ie

      - name: Saucelabs Disconnect
        run: ./scripts/sauce_connect_teardown.sh
