
name: Travis CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests against travis-ci
        uses: ktomk/run-travis-yml@v1
        with:
          file: .travis.yml
          steps: |
            install
            script
          allow-failure: false
